CREATE TABLE IF NOT EXISTS assets (
  id SERIAL PRIMARY KEY,
  asset_type_id INTEGER,
  asset_type VARCHAR(100),
  owner_id INTEGER,
  asset_name VARCHAR(255) NOT NULL,
  asset_code VARCHAR(50) UNIQUE,
  business_owner VARCHAR(255),
  technical_owner VARCHAR(255),
  department VARCHAR(255),
  data_classification VARCHAR(50),
  access_level VARCHAR(50),
  authentication_method VARCHAR(50),
  supports_critical_service BOOLEAN DEFAULT FALSE,
  hosting VARCHAR(100),
  rto_hours NUMERIC(10,2),
  rpo_hours NUMERIC(10,2),
  criticality VARCHAR(100) NOT NULL,
  internet_exposed BOOLEAN DEFAULT FALSE,
  backup_enabled BOOLEAN DEFAULT FALSE,
  encryption_enabled BOOLEAN DEFAULT FALSE,
  mfa_enabled BOOLEAN DEFAULT FALSE,
  logging_enabled BOOLEAN DEFAULT FALSE,
  logging_to_siem VARCHAR(500),
  edr_endpoint_security VARCHAR(500),
  vuln_scanning VARCHAR(500),
  backup_method VARCHAR(500),
  country VARCHAR(100),
  region VARCHAR(100),
  key_users_customers VARCHAR(500),
  edr_enabled BOOLEAN DEFAULT FALSE,
  vuln_scanning_enabled BOOLEAN DEFAULT FALSE,
  cmdb_ci_id VARCHAR(100),
  notes TEXT,
  status VARCHAR(50) DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS threat_catalog (
  id SERIAL PRIMARY KEY,
  threat_id VARCHAR(50) UNIQUE,
  threat_name VARCHAR(255),
  threat_source VARCHAR(100),
  threat_category VARCHAR(100),
  description TEXT,
  stride_category VARCHAR(50),
  nist_csf_function VARCHAR(50),
  nist_csf_category VARCHAR(50),
  applicable_asset_types TEXT[],
  reference_url VARCHAR(500),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS threat_asset_type_mapping (
  id SERIAL PRIMARY KEY,
  asset_type VARCHAR(100),
  threat_id VARCHAR(50) REFERENCES threat_catalog(threat_id) ON DELETE CASCADE,
  applicability_score INTEGER,
  is_applicable BOOLEAN DEFAULT TRUE,
  notes TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS risk_register (
  id SERIAL PRIMARY KEY,
  risk_id VARCHAR(50) UNIQUE,
  asset_id INTEGER REFERENCES assets(id) ON DELETE SET NULL,
  threat_id VARCHAR(50) REFERENCES threat_catalog(threat_id),
  risk_title VARCHAR(255),
  risk_description TEXT,
  vulnerability_description TEXT,
  threat_actor VARCHAR(100),
  attack_vector VARCHAR(100),
  nist_csf_function VARCHAR(50),
  nist_csf_category VARCHAR(50),
  department_control_owner VARCHAR(255),
  risk_owner VARCHAR(255),
  assessed_by VARCHAR(255),
  notes TEXT,
  status VARCHAR(50) DEFAULT 'Open',
  risk_treatment VARCHAR(20),
  treatment_rationale TEXT,
  treatment_owner VARCHAR(255),
  treatment_date DATE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS risk_analysis (
  id SERIAL PRIMARY KEY,
  risk_id INTEGER REFERENCES risk_register(id) ON DELETE CASCADE UNIQUE,
  likelihood INTEGER CHECK (likelihood BETWEEN 1 AND 5),
  likelihood_label VARCHAR(50),
  likelihood_rationale TEXT,
  impact INTEGER CHECK (impact BETWEEN 1 AND 5),
  impact_label VARCHAR(50),
  impact_rationale TEXT,
  risk_score INTEGER,
  risk_level VARCHAR(20),
  inherent_likelihood INTEGER CHECK (inherent_likelihood BETWEEN 1 AND 5),
  inherent_likelihood_label VARCHAR(50),
  inherent_impact INTEGER CHECK (inherent_impact BETWEEN 1 AND 5),
  inherent_impact_label VARCHAR(50),
  inherent_risk_score INTEGER,
  inherent_risk_level VARCHAR(20),
  inherent_likelihood_rationale TEXT,
  inherent_impact_rationale TEXT,
  inherent_calculation_method VARCHAR(50) DEFAULT 'automated',
  inherent_assessor_override BOOLEAN DEFAULT FALSE,
  inherent_review_status VARCHAR(50) DEFAULT 'Needs Inherent Review',
  inherent_assessed_at TIMESTAMP,
  confidentiality_impact BOOLEAN DEFAULT FALSE,
  integrity_impact BOOLEAN DEFAULT FALSE,
  availability_impact BOOLEAN DEFAULT FALSE,
  business_impact_description TEXT,
  assessed_by VARCHAR(255),
  assessment_date TIMESTAMP,
  asset_criticality_weight NUMERIC(5,2),
  residual_risk_score INTEGER,
  residual_risk_level VARCHAR(20),
  residual_calculated_at TIMESTAMP,
  control_effectiveness INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS scf_controls (
  id SERIAL PRIMARY KEY,
  scf_control_id VARCHAR(50) UNIQUE NOT NULL,
  scf_domain VARCHAR(100),
  scf_control_name VARCHAR(255),
  scf_description TEXT,
  nist_csf_function VARCHAR(50),
  nist_csf_category VARCHAR(50),
  implementation_note TEXT,
  priority INTEGER DEFAULT 3,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS control_recommendations (
  id SERIAL PRIMARY KEY,
  risk_analysis_id INTEGER REFERENCES risk_analysis(id) ON DELETE CASCADE,
  risk_register_id INTEGER REFERENCES risk_register(id) ON DELETE CASCADE,
  scf_control_id VARCHAR(50),
  scf_domain VARCHAR(100),
  implementation_priority VARCHAR(20),
  recommendation_rationale TEXT,
  implementation_status VARCHAR(50) DEFAULT 'not_started',
  assigned_to VARCHAR(255),
  target_impl_date DATE,
  actual_impl_date DATE,
  evidence_file_path TEXT,
  evidence_original_name VARCHAR(255),
  evidence_uploaded_at TIMESTAMP,
  approval_status VARCHAR(20) DEFAULT 'pending',
  approved_by VARCHAR(255),
  approved_at TIMESTAMP,
  approval_notes TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);
